### ISSUE TITLE
Internal Review Checklist

### ISSUE THREAD

**Issue by rabernat** [m2lines/L96_demo#12]
To claim a notebook, please reply to this issue and I will tag you for it.

### Review Process

Each reviewer should do the following for their assigned notebook

- Install the specified development environment (part of #11) on their local machine
- Open their assigned notebook in jupyterlab and click "restart kernel and run all cells". The notebook should run from start to finish with no errors (warnings are fine).
- If any errors are encountered, **open a new github issue**. The errors should be fixed either by the original author, the reviewer, or anyone else who sees how to fix it. The fix should be submitted via a **pull request** (see below for details).
- Once the notebook is running without errors, we move to the stylistic review. Some aspects to consider
  - Is the notebook free from spelling and grammar errors?
  - Is the text clear, relatively free of jargon, and understandable to a general audience?
  - Does the notebook contain appropriate references, both to external papers and other notebooks within the book?
  - Are the figures clear and looking good?
- The reviewer should feel free to directly edit the notebook to resolve any issues. Changes should be made via **pull request**.
- Once all of the above are complete, check off the box below corresponding to the assigned notebook 

### Notebook Checklist

(Please do not check them off until the review is completed.)

- [ ] [01Intro](https://github.com/m2lines/L96_demo/tree/main/01Intro) @WillyChap @bhouri0412 
- [ ] [02type-of-parametrization](https://github.com/m2lines/L96_demo/tree/main/02type-of-parametrization) @adconnolly @bhouri0412 
- [ ] [03Data-Assimilation](https://github.com/m2lines/L96_demo/tree/main/03Data-Assimilation) @William-gregory
- [x] [04Subgrid-parametrization-pytorch](https://github.com/m2lines/L96_demo/tree/main/04Subgrid-parametrization-pytorch) @anastasiaGor @dante831 
- [ ] [05Offline-DA-increments](https://github.com/m2lines/L96_demo/tree/main/05Offline-DA-increments) @William-gregory 
- [ ] [06Different-ML-models](https://github.com/m2lines/L96_demo/tree/main/06Different-ML-models) @Sshamekh 
- [ ] [07-Interpretability-of-ML](https://github.com/m2lines/L96_demo/tree/main/07-Interpretability-of-ML) @dhruvbalwada @asross 
- [ ] [08-Implementation](https://github.com/m2lines/L96_demo/tree/main/08-Implementation) @Pperezhogin @jejjohnson 
- [ ] [09-models-tuning](https://github.com/m2lines/L96_demo/tree/main/09-models-tuning) @lzampier

### How to make a pull request

We will follow [these general instructions](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/)

1. Click "fork" from github
2. Clone your fork from your local computer
3. Create a new branch for your feature and switch to it
4. Make your changes and commit them
5. Push your branch to your fork on GitHub
6. Create a pull request vai GitHub

**Comment by LaureZanna** [comment]
> 

Hi @lzampier , did you end up writing a notebook for the model tuning? No worries if you did ! We are just checking. Thx.
